FROM python:3.8-alpine

MAINTAINER obianaifeanyi@gmail.com

RUN apt-get update

CMD ["echo", """
..........................
<    I am a hourse    >
..........................
            
            \       ^ _ ^
             \     ( o o )
                   ( ___ ) \________________    
                        \                    ) \/\
                         
                         | |--------------W  |
                         | |              |  |
              
"""]
